/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/forum-list:
  controller: main
  action: forumList

/forum:
  controller: main
  action: forum

/rating:
  controller: main
  action: rating

/rating-list:
  controller: main
  action: ratingList

/login:
    controller: user
    action: login

/logout:
    controller: user
    action: logout

/register:
    controller: user
    action: register

/forget:
    controller: user
    action: pwdforget

/reset-password:
    controller: user
    action: pwdReset

/activation:
    controller: user
    action: activatedaccount

/user-setting:
  controller: user
  action: userSetting

/dashboard:
    controller: admin
    action: dashboard
    security:
        - admin

/user-management:
    controller: admin
    action: usermanagement
    security:
        - admin

/role-management:
    controller: admin
    action: managerole
    security:
        - admin

/page-management:
    controller: admin
    action: managepage
    security:
        - admin

/page-creation:
    controller: admin
    action: creationpage
    security:
        - admin

/donation:
    controller: main
    action: donation

/palier-donation:
    controller: admin
    action: palierdonation
    security:
        - admin

/forum-management:
  controller: admin
  action: forumManagement
  security:
    - admin

/ban-word-management:
  controller: admin
  action: banWord
  security:
    - admin

/message-management:
  controller: admin
  action: messageManagement
  security:
    - admin

/warning-management:
  controller: admin
  action: warningManagement
  security:
    - admin

/tag:
  controller: admin
  action: tag
  security:
    - admin
    
/config:
    controller: config
    action: config

/api-configuration:
    controller: admin
    action: api

/search:
    controller: search
    action: search

/notification:
    controller: notification
    action: notification

/template-edit:
  controller: admin
  action: templateEdition
  security:
    - admin

/template-save:
  controller: admin
  action: saveStyle
  security:
    - admin