/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/activation:
  controller: user
  action: activatedaccount

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin

/usermanagement:
  controller: admin
  action: usermanagement
  security:
    - admin

/roleManagement:
  controller: admin
  action: managerole
  security:
    - admin

/pageManagement:
  controller: admin
  action: managepage
  security:
    - admin

/pageCreation:
  controller: admin
  action: creationpage
  security:
    - admin